# Generated by Django 4.1 on 2022-08-17 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_currencyamount_delete_currencyamout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingscreen',
            name='user',
            field=models.ManyToManyField(related_name='trading_screens', to=settings.AUTH_USER_MODEL),
        ),
    ]
