# Generated by Django 4.1 on 2022-08-17 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_tradingscreen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingscreen',
            name='user',
        ),
        migrations.AddField(
            model_name='tradingscreen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_screens', to=settings.AUTH_USER_MODEL),
        ),
    ]
