# Generated by Django 4.1 on 2022-08-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_tradingscreen_user_tradingscreen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyamount',
            name='trading_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tradingscreen'),
        ),
    ]
