# Generated by Django 3.2.7 on 2021-10-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
