# Generated by Django 4.1 on 2022-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direction',
            field=models.CharField(default='buy', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='fullfilled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
