# Generated by Django 4.1 on 2022-08-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_order_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyamount',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_balance',
            field=models.FloatField(default=0),
        ),
    ]
