# Generated by Django 4.1 on 2022-08-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_currencyamount_user_order_updated_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated_balance',
            new_name='last_balance',
        ),
    ]
