# Generated by Django 4.1 on 2022-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_updated_balance_order_last_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trigger_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
