# Generated by Django 3.2.7 on 2022-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220109_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_plan',
            field=models.CharField(choices=[('PREMIUM', 'Plan Premium'), ('MEDIUM', 'Plan Medium'), ('STARTER', 'Plan Starter')], default='STARTER', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
