# Generated by Django 4.1 on 2022-09-06 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_order_limit_order_trigger_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyamount',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
