# Generated by Django 3.2.7 on 2022-03-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_id'),
        ('account', '0012_auto_20220314_0902'),
    ]

    operations = [
    ]
