# Generated by Django 4.1 on 2022-09-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_currencyamount_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.currencyamount'),
        ),
    ]
