# Generated by Django 4.1 on 2022-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_order_last_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trigger_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_of_order',
        ),
        migrations.AddField(
            model_name='order',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('SHORT', 'Short Selling'), ('LONG', 'Buy Long')], default='LONG', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
