# Generated by Django 4.1 on 2022-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_order_amount_remove_order_direction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fullfilled_on',
            new_name='position_closed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='order_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='position_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='take_profit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
