# Generated by Django 4.1 on 2022-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_order_external_id_order_external_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='external_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
