# Generated by Django 4.1 on 2022-11-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_order_external_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingscreen',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
