# Generated by Django 4.1 on 2022-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('none', 'No Api'), ('krkn', 'Kraken')], default='none', max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('none', 'No Api'), ('krkn', 'Kraken')], default='none', max_length=4)),
                ('authentication', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('symbol', models.CharField(default='', max_length=255)),
                ('currency_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_1', to='exchange.currency')),
                ('currency_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_2', to='exchange.currency')),
            ],
        ),
    ]
