# Generated by Django 4.0.6 on 2022-08-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=255)),
                ('currency_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_1', to='exchange.currency')),
                ('currency_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_2', to='exchange.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication', models.JSONField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange'),
        ),
    ]
