# Generated by Django 4.1 on 2022-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.CharField(choices=[('none', 'No Api'), ('krkn', 'Kraken')], default='none', max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangeapi',
            name='exchange',
            field=models.CharField(choices=[('none', 'No Api'), ('krkn', 'Kraken')], default='none', max_length=4),
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
