# Generated by Django 4.1 on 2022-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
