# Generated by Django 4.1 on 2022-08-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_pair_last_updated_pair_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='value',
        ),
        migrations.CreateModel(
            name='PairValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='exchange.pair')),
            ],
        ),
    ]
