# Generated by Django 4.1 on 2022-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_pair_value_pairvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='PairValue',
        ),
    ]
