# Generated by Django 4.1 on 2022-08-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_pair_value_delete_pairvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='previous_value',
            field=models.FloatField(default=0),
        ),
    ]
